#!/bin/bash
### BEGIN INIT INFO
#
# Provides:		start-gw.py
# Required-Start:	$all
# Required-Stop:	
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	start-gw.py initscript

#
### END INIT INFO
## Fill in name of program here.
PROG_PATH="/home/pi/lora-gw/gw_full_latest"
PROG="$PROG_PATH/start_gw.py"

PROG_ARGS=""
PIDFILE="/var/run/start_gw.pid"

start() {
      if [ -e $PIDFILE ]; then
          ## Program is running, exit with error.
          echo "Error! $PROG is currently running!" 1>&2
      else
          #$PROG $PROG_ARGS 2>&1 >/dev/null
          #start-stop-daemon --start --quiet --background --oknodo -m -r $CHROOT --pidfile $PIDFILE --exec $PROG -- $PROG_ARGS
          start-stop-daemon --start --quiet --background --oknodo -m --pidfile $PIDFILE --exec $PROG -- $PROG_ARGS
          echo "$PROG started"
          #touch $PIDFILE
      fi
}

stop() {
      if [ -e $PIDFILE ]; then
         echo "$PROG is running"
         #killall $PROG
         sudo kill $(ps aux | grep -e start_gw -e lora_gateway -e post_processing -e log_gw | awk '{print $2}')
         start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
         rm -f $PIDFILE
         echo "$PROG stopped"
      else
          ## Program is not running, exit with error.
          echo "Error! $PROG not started!" 1>&2
      fi
}

## Check to see if we are running as root first.
## Found at http://www.cyberciti.biz/tips/shell-root-user-check-script.html
#if [ "$(id -u)" != "0" ]; then
#      echo "This script must be run as root" 1>&2
#      exit 1
#fi

case "$1" in
      start)
          start
          exit 0
      ;;
      stop)
          stop
          exit 0
      ;;
      reload|restart|force-reload)
          stop
          start
          exit 0
      ;;
      **)
          echo "Usage: $0 {start|stop|reload}" 1>&2
          exit 1
      ;;
esac
#
